name = "Kwat"
uuid = "1fe83854-81c0-42f7-afc9-71ba9af673ca"
authors = ["KwatMDPhD <kwat.me@icloud.com>"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
