name = "Kwat"
uuid = "fb31f113-4a63-4a8e-817a-4bdffc7e605a"
authors = ["KwatMDPhD <kwat.me@icloud.com>"]
version = "0.2.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.6"
